baseURL = 'https://jshbadger.github.io/'
languageCode = 'en-us'
title = 'Jacob Stewart'
theme = 'typo'
enableGitInfo = true

[frontmatter]
lastmod = ['lastmod', ':fileModTime', ':default']

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "Personal Info and Portfolio"


# Appearance settings
theme = 'auto'
colorPalette = 'gruvebox'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Jacob Stewart'
homeIntroContent = """
![Headshot](/img/JacobHeadshot.jpg)

Hello! I am Jacob Stewart, a PhD student in Electrical Engineering at the University of Colorado at Boulder. My interests are mostly in technology, with particular interest in presenting information effectively, working efficiently, and understanding the nuances. My goal going into engineering was to be able to build anything. Now I want to build it better.

You can learn more about me on the [About page]({{< ref "/about/index.md" >}}), [contact me]({{< ref "/contact/index.md" >}}), or check out the [projects]({{< ref "/projects/" >}}) I have completed and am currently working on.
"""
# Is it "in" or "of" for undergraduate ___ EE

# Collection to display on home
# homeCollectionTitle = 'Projects'
# homeCollection = '/projects'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2006 Jan 02'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "email"
url = "mailto:stewar.jacob@proton.me"

[[params.social]]
name = "github"
url = "https://github.com/jshbadger"

# Main menu pages
[[params.menu]]
name = "Home"
url = "/"

[[params.menu]]
name = "About"
url = "/about/"

[[params.menu]]
name = "Contact"
url = "/contact/"

[[params.menu]]
name = "Projects"
url = "/projects/"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
